from flask import Flask, json
from flask import request
from chatbot import respond
from corpus import inicialize_medium_corpus  # Corrected import
from evaluation import evaluate

app = Flask(__name__)

history = [
    {
        "bot": {
            "ID": "1",
            "Intent": "General",
            "Question_Text": "Hi! I’m here to help you explore your skills and interests. Ready to start?",
            "example_responses": {"0": "no", "00": "yes"},
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Value Identification",
                "Goal Setting",
                "Activity Preference",
                "Personal Reflection",
                "Interest Expansion",
                "Learning Style",
                "Learning Style",
                "Learning Style",
                "Personality",
                "Personality",
                "Work Environment",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Strengths",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": "Yes, I'm ready",
    },
    {
        "bot": {
            "ID": "16",
            "Intent": "Work Environment",
            "Question_Text": "Do you thrive in a competitive or collaborative work environment?",
            "example_responses": {
                "1": "I don’t like working in any environment.",
                "2": "I can tolerate competitive environments but don’t prefer them.",
                "3": "I don’t mind a mix of competitive and collaborative work.",
                "4": "I excel in collaborative work environments.",
                "5": "I thrive in highly competitive settings and love challenges.",
            },
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Value Identification",
                "Goal Setting",
                "Activity Preference",
                "Personal Reflection",
                "Interest Expansion",
                "Learning Style",
                "Learning Style",
                "Learning Style",
                "Personality",
                "Personality",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Strengths",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": "I'm more of a collaborative person",
    },
    {
        "bot": {
            "ID": "9",
            "Intent": "Personal Reflection",
            "Question_Text": "If you could choose any job without thinking about money, what would it be?",
            "example_responses": {
                "1": "I haven’t thought about it.",
                "2": "Maybe something simple like gardening.",
                "3": "A teacher or mentor role.",
                "4": "A career in art or music.",
                "5": "Running my own non-profit organization.",
            },
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Value Identification",
                "Goal Setting",
                "Activity Preference",
                "Interest Expansion",
                "Learning Style",
                "Learning Style",
                "Learning Style",
                "Personality",
                "Personality",
                "Work Environment",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Strengths",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": "Money is the most important factor for me",
    },
    {
        "bot": {
            "ID": "10",
            "Intent": "Interest Expansion",
            "Question_Text": "Would you like to explore careers related to your interests or try something completely new?",
            "example_responses": {
                "1": "I’m not interested in exploring careers.",
                "2": "I might try something new.",
                "3": "I’d like to explore a mix of both.",
                "4": "I’m keen on exploring careers related to my interests.",
                "5": "I’m determined to pursue my passion and interests in depth.",
            },
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Value Identification",
                "Goal Setting",
                "Activity Preference",
                "Personal Reflection",
                "Learning Style",
                "Learning Style",
                "Learning Style",
                "Personality",
                "Personality",
                "Work Environment",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Strengths",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": "Something completely new",
    },
    {
        "bot": {
            "ID": "6",
            "Intent": "Value Identification",
            "Question_Text": "What’s more important to you: creativity, logic, or helping others?",
            "example_responses": {
                "1": "I don’t have a strong opinion.",
                "2": "I value creativity a little more.",
                "3": "Logic is somewhat important to me.",
                "4": "Helping others is very important to me.",
                "5": "All three are extremely important to me.",
            },
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Goal Setting",
                "Activity Preference",
                "Personal Reflection",
                "Interest Expansion",
                "Learning Style",
                "Learning Style",
                "Learning Style",
                "Personality",
                "Personality",
                "Work Environment",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Strengths",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": "Helping others",
    },
    {
        "bot": {
            "ID": "20",
            "Intent": "Strengths",
            "Question_Text": "What would you say is your greatest strength?",
            "example_responses": {
                "1": "I don’t think I have any strengths.",
                "2": "I’m decent at problem-solving.",
                "3": "I’m good at organizing tasks.",
                "4": "I’m great at leading teams.",
                "5": "I excel in creative thinking and innovation.",
            },
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Value Identification",
                "Goal Setting",
                "Activity Preference",
                "Personal Reflection",
                "Interest Expansion",
                "Learning Style",
                "Learning Style",
                "Learning Style",
                "Personality",
                "Personality",
                "Work Environment",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": "Helping others",
    },
    {
        "bot": {
            "ID": "11",
            "Intent": "Learning Style",
            "Question_Text": "How do you prefer to learn new things?",
            "example_responses": {
                "1": "I don’t like learning new things.",
                "2": "I learn better when someone explains things to me.",
                "3": "I like learning through trial and error.",
                "4": "I prefer hands-on learning experiences.",
                "5": "I enjoy a mix of research, hands-on work, and structured classes.",
            },
            "following_intent": [
                "Interest Identification",
                "Interest Identification",
                "Skill Discovery",
                "Skill Discovery",
                "Value Identification",
                "Goal Setting",
                "Activity Preference",
                "Personal Reflection",
                "Interest Expansion",
                "Personality",
                "Personality",
                "Work Environment",
                "Career Exploration",
                "Career Exploration",
                "Career Exploration",
                "Strengths",
                "Challenges",
                "Challenges",
                "Lifestyle",
                "Goals",
                "Goals",
                "Values",
                "Values",
                "Purpose",
                "Flexibility",
                "Location",
            ],
        },
        "client": None,
    },
]  # this will eitherbe stored on the client side (local sotrage) or db
corpus = inicialize_medium_corpus()
used_question_idx = []


@app.route("/respond")
def respond_route():
    client_response = request.args.get("res")

    if client_response and history:
        print(client_response)
        # Update the last entry in the history with the client's response
        history[-1]["client"] = client_response

    return_response = respond(history, corpus, used_question_idx)
    print(return_response)

    return json.dumps(
        {"response": history[-1]["bot"]["Question_Text"], "history": history}
    )


@app.route("/eval")
def eval():
    scores = evaluate(history)
    return json.dumps({"response": "evaluation is done", "scores": scores})


if __name__ == "__main__":
    app.run()
